# netlify.toml

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "https://blog.williamthresher.com/blog/post"
  to = "https://williamthresher.com/blog/post"
  status = 200
  
  [[redirects]]
  from = "https://blog.williamthresher.com/blog/about"
  to = "https://williamthresher.com/blog/about"
  status = 200
  
  [[redirects]]
  from = "https://blog.williamthresher.com/blog/tags"
  to = "https://williamthresher.com/blog/tags"
  status = 200
