# netlify.toml

[[redirects]]
  from = "https://blog.williamthresher.com/blog/post"
  to = "https://williamthresher.com/blog/post"
  status = 200
  force = true  #COMMENT: ensure that we always redirect
  
  [[redirects]]
  from = "https://blog.williamthresher.com/blog/about"
  to = "https://williamthresher.com/blog/about"
  status = 200
  force = true  #COMMENT: ensure that we always redirect
  
  [[redirects]]
  from = "https://blog.williamthresher.com/blog/tags"
  to = "https://williamthresher.com/blog/tags"
  status = 200
  force = true  #COMMENT: ensure that we always redirect

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
