# netlify.toml

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/blog/post"
  to = "https://williamthresher.com/blog/:splat"
  status = 200
  
  [[redirects]]
  from = "/blog/about"
  to = "https://williamthresher.com/blog/:splat"
  status = 200
  
  [[redirects]]
  from = "/blog/tags"
  to = "https://williamthresher.com/blog/:splat"
  status = 200
